apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-{{ .Values.app_name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  {{- toYaml .Values.config_map | nindent 2 }}

