apiVersion: v1
kind: Service
metadata:
  name: roboshop-{{ .Values.app_name }}
spec:
  type: {{ .Values.service_type | default "ClusterIP" }}
  selector:
    app: roboshop-{{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app_port }} # Service Port
      targetPort: {{ .Values.app_port }} # Container Port

