apiVersion: v1
kind: Service
metadata:
  name: roboshop-{{ .Values.app_name }}
spec:
  selector:
    app: roboshop-{{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app_port }} # Service Port
      targetPort: {{ .Values.app_port }} # Container Port

